language: node_js
cache:
  directories:
    - $HOME/.npm
notifications:
  email: false
node_js:
  - '10.15.3'
before_script:
  - npm prune
script:
  - npm run test:single  
after_success:
  - npm run semantic-release
branches:
  except:
    - /^v\d+\.\d+\.\d+$/